name: Docker Compose Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Navigate to app folder and build Docker images
        working-directory: ./app
        run: docker compose build

      - name: Start containers
        working-directory: ./app
        run: docker compose up -d

      - name: Wait for the app to be ready
        working-directory: ./app
        run: |
          for i in {1..10}; do
            curl -s http://localhost:5000/ping && break || sleep 3
          done

      - name: Test /ping endpoint
        run: curl -v http://localhost:5000/ping

      - name: Test /users endpoint
        run: curl -v http://localhost:5000/users

      - name: Shut down containers
        if: always()
        working-directory: ./app
        run: docker compose down
